Support k8s >1.18
Fixes...
```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```
on newer versions of k8s. It was deprecated in 1.16 and removed in 1.18